yolo_model:

  config_file:
    name: obj.cfg
  weight_file:
    name: simple_7100.weights
  threshold:
    value: 0.7
  detection_classes:
    names:
      - plate_red_metal
      - coffee_el_bryg
      - cup_eco_orange
      - fork_blue_plastic
      - fork_red_plastic
      - corn_flakes_kelloggs
      - knife_red_plastic
      - knife_blue_plastic
      - meer_salz
      - icetea_pfanner_pfirsich
      - plate_blue_metal
      - reine_butter_milch
      - sigg_bottle
      - soja_milch
      - voll_milch
